site_name: GSR
site_autor: Jean Matheus
site_url: https://JeanDev0.github.io/doce-gsr/

theme:
  name: material
  language: pt

  features:
    - content.action.edit
    - content.action.view
  palette:
    primary: red
    accent: red